name: "AI PR Reviewer"
description: "Uses Azure OpenAI to review diffs, then posts code review comments on GitHub PRs."
author: "Propstreet"
runs:
  using: "node20"
  main: "dist/index.js" # compiled output

inputs:
  exclude:
    description: "Glob patterns to exclude files from review (e.g. '*.test.ts' or 'dist/**/*')"
    required: false
    default: ""
  azureOpenAIEndpoint:
    description: "Azure OpenAI endpoint (e.g., https://your-resource.openai.azure.com/openai/deployments/...)"
    required: true
  azureOpenAIDeployment:
    description: "Azure OpenAI deployment (e.g., your-resource)"
    required: true
  azureOpenAIKey:
    description: "API key for Azure OpenAI"
    required: true
  azureOpenAIVersion:
    description: "Azure OpenAI version (e.g., 2024-12-01-preview)"
    required: false
    default: "2024-12-01-preview"
  base:
    description: "Base commit SHA to compare against."
    required: false
  head:
    description: "Head commit SHA to compare against."
    required: false
  severity:
    description: "Minimum severity level required to post a request changes review comment (info, warning, or error)."
    required: false
    default: "error"
  reasoningEffort:
    description: "Reasoning effort level (low, medium, or high)."
    required: false
    default: "medium"
  tokenLimit:
    description: "Maximum number of tokens to process."
    required: false
    default: "50000"
  commitLimit:
    description: "Maximum number of commits to load for 'entire-pr' diff mode."
    required: false
    default: "100"
