# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

description: "Generate GitHub PR review comments using Azure Open AI"

defaultTest:
  options:
    # Used for grading
    provider: file://providers/provider-gpt4o.yaml

prompts:
  - raw: file://./prompts/review-o1.json
    label: review-o1
    config:
      response_format: file://./prompts/review-format.json
  - raw: file://./prompts/review-gpt4o.json
    label: review-gpt4o
    config:
      response_format: file://./prompts/review-format.json

providers:
  - id: azureopenai:chat:{{env.AZURE_OPENAI_GPT4O_DEPLOYMENT}}
    label: gpt4o
    config:
      apiVersion: 2024-08-01-preview
    prompts:
      - review-gpt4o
  - id: azureopenai:chat:{{env.AZURE_OPENAI_O1_DEPLOYMENT}}
    label: o1-low
    config:
      apiVersion: 2024-12-01-preview
      reasoning_effort: "low"
      o1: true
    prompts:
      - review-o1
  - id: azureopenai:chat:{{env.AZURE_OPENAI_O1_DEPLOYMENT}}
    label: o1-medium
    config:
      apiVersion: 2024-12-01-preview
      reasoning_effort: "medium"
      o1: true
    prompts:
      - review-o1
  - id: azureopenai:chat:{{env.AZURE_OPENAI_O1_DEPLOYMENT}}
    label: o1-high
    config:
      apiVersion: 2024-12-01-preview
      reasoning_effort: "high"
      o1: true
    prompts:
      - review-o1

tests:
  - vars:
      commitMessage: "Add subtract method to calculator"
      diff: file://./prompts/review-1.md
    description: "Comment on use of any"
    options:
      # Parse the JSON before all assertions
      transform: JSON.parse(output)
    assert:
      - type: is-json
        value:
          {
            "required": ["comments"],
            "type": "object",
            "properties": { "comments": { "type": "array", "minItems": 1 } },
          }
      - type: javascript
        value: |
          output.comments[0].comment.includes("any") && [7,8,9].some(l => l === output.comments[0].line) && output.comments[0].file === "src/example.ts" && output.comments[0].severity === "warning"

