# yaml-language-server: $schema=https://promptfoo.dev/config-schema.json

description: "Generate GitHub PR review comments using Azure Open AI"

defaultTest:
  options:
    # Used for grading
    provider: file://providers/provider-gpt4o.yaml

prompts:
  - raw: file://./prompts/review-reasoning.json
    label: review-reasoning
    config:
      response_format: file://./prompts/review-format.json
  - raw: file://./prompts/review-gpt4o.json
    label: review-gpt4o
    config:
      response_format: file://./prompts/review-format.json

providers:
  - id: azure:chat:{{env.AZURE_OPENAI_GPT4O_DEPLOYMENT}}
    label: gpt4o
    config:
      apiVersion: 2025-03-01-preview
    prompts:
      - review-gpt4o
  - id: azure:chat:{{env.AZURE_OPENAI_REASONING_DEPLOYMENT}}
    label: reasoning-low
    config:
      apiVersion: 2025-03-01-preview
      reasoning_effort: "low"
      isReasoningModel: true
    prompts:
      - review-reasoning
  - id: azure:chat:{{env.AZURE_OPENAI_REASONING_DEPLOYMENT}}
    label: reasoning-medium
    config:
      apiVersion: 2025-03-01-preview
      reasoning_effort: "medium"
      isReasoningModel: true
    prompts:
      - review-reasoning
  - id: azure:chat:{{env.AZURE_OPENAI_REASONING_DEPLOYMENT}}
    label: reasoning-high
    config:
      apiVersion: 2025-03-01-preview
      reasoning_effort: "high"
      isReasoningModel: true
    prompts:
      - review-reasoning

tests:
  - vars:
      commitMessage: "Add subtract method to calculator"
      diff: file://./prompts/review-1.md
    description: "Comment on use of any"
    options:
      # Parse the JSON before all assertions
      transform: JSON.parse(output)
    assert:
      - type: is-json
        value:
          {
            "required": ["comments"],
            "type": "object",
            "properties": { "comments": { "type": "array", "minItems": 1 } },
          }
      - type: javascript
        value: |
          output.comments[0].comment.includes("any") && output.comments[0].line === 7 && output.comments[0].file === "src/example.ts" && output.comments[0].severity === "warning"
